### ISSUE TITLE
Time Travelling does not work

### ISSUE THREAD

**Issue by supasate** [supasate/connected-react-router#1]
With Redux DevTools, everything seems to work well except time travelling.

**Comment by dictions** [comment]
Hey there, I think I can tackle this since it's blocking for me. Any insight as to why this might be?

**Comment by supasate** [comment]
Nice catch!

`ConnectedRouter.js` should be changed like you proposed.

Can we just create a history instance in `reducer.js` like the below code instead of passing `history` object to it? So, it'll be easier for setting up the root reducer; especially, we we make `rootReducer' as a separate file.

``` javascript
import { createBrowserHistory } from 'history'
import { LOCATION_CHANGE } from './actions'

/**
 * This reducer will update the state with the most recent location history
 * has transitioned to.
 */
const history = createBrowserHistory()
const initialState = {
  location: history.location,
  action: history.action,
}

const routerReducer = (state = initialState, { type, payload } = {}) => {
  if (type === LOCATION_CHANGE) {
    return {
      ...state,
      ...payload,
    }
  }

  return state
}

export default routerReducer
```

**Comment by dictions** [comment]
@supasate I thought about that, but I have reservations because:

1. It becomes less testable because we're using `createBrowserHistory` which is dependent on `window` right?
2. We need to expose the `history` object somehow so that `StaticRouter` has access to it, right?

If we passed it in, it could be mocked in a testing environment, and we would give `StaticRouter` access to it for `push`, `replace`, etc.

**Comment by supasate** [comment]
@dictions I agree with testability.  

The `history` object need to be passed to `Provider`, `store`, and `rootReducer`. If they are in separated files, the `rootReducer` might need to be transformed to a function that takes `history` object in. 

However, I'd like make it simple by not changing the way most people do with the `rootReducer` file with the benefit of only initial state in the reducer. 

I'll rethink it this weekend probably. If you have any idea, please let me know!

**Comment by dictions** [comment]
Yeah it's a tricky one. You either have to pass it to your `rootReducer` and make that a generator. Or, you'll need to create and colocate history with your `rootReducer`, making it not testable in the same way. What if the API was similar to redux `connect`?

```
// Your main client entrypoint

import rootReducer from 'reducers'
import configureStore from './store'
import {connectRouter} from 'connected-react-router'
import {createBrowserHistory} from 'history'

const history = createBrowserHistory()
const store = configureStore(
  connectRouter(history)(rootReducer)
)

// Set up router ...
```

Is that too ridiculous?

**Comment by supasate** [comment]
@dictions I think it's a nice solution. Based on your code, I fixed some bugs and Time Travel works great now (except URL bar is not updated which we may fix it as another issue).

```javascript
import { LOCATION_CHANGE } from './actions'

/**
 * This reducer will update the state with the most recent location history
 * has transitioned to.
 */
const routerReducer = (state, { type, payload } = {}) => {
  if (type === LOCATION_CHANGE) {
    return {
      ...state,
      ...payload,
    }
  }

  return state
}

const connectRouter = (history) => {
  const initialRouterState = {
    location: history.location,
    action: history.action,
  }
  // Wrap a root reducer and return a new root reducer with router state
  return (rootReducer) => (state, action) => {
    let routerState = initialRouterState

    // Extract router state
    if (state) {
      const { router, ...rest} = state
      routerState = router || routerState
      state = rest
    }
    const reducerResults = rootReducer(state, action)

    return {
      ...reducerResults,
      router: routerReducer(routerState, action)
    }
  }
}

export default connectRouter
```

Would you like to submit a PR to be a contributor of this idea?

**Comment by dictions** [comment]
Looks great! I'll submit a PR in a bit. 

I noticed that the URL bar was out of sync w/ the router reducer. I can't seem to figure out a solution to that though, as it would involve sending undo payloads to the browser history, and keeping track of the "real" browser history in memory. 

My best example would be this:
1. Start on Page A
2. Nagivate to Page B
3. Go back in browser history to Page A (Page B is forward in history now). 
4. "Undo" the navigate change via the Redux Devtools LogMonitor, thereby going _forward_ to Page B.

I can't seem to wrap my head around a simple solution there. If you can figure it out I'd love to hear ideas.

PR coming soon!

**Comment by supasate** [comment]
About synchronizing URL in Time Travel mode, I've created a new issue #8 for this topic.
