### ISSUE TITLE
Incorrect Typescript type definitions

### ISSUE THREAD

**Issue by Hardtack** [supasate/connected-react-router#103]
The current type definition of `connectRouter()` is like this:

``` typescript
  export function connectRouter(history: History)
    : <S>(reducer: Reducer<S>) => Reducer<S>
```

But, since `connectRouter` injects the key `router` with value of `RouterState`, the returned reducer's type should be `Reducer<S & { reducer: RouterState }>`

So, I think, may this be correct

``` typescript
  export function connectRouter(history: History)
    : <S>(reducer: Reducer<S>) => Reducer<S & { router: RouterState }>
```

**Comment by supasate** [comment]
Fixed! Thanks for reporting!
