### ISSUE TITLE
No reducer provided for key "routing"

### ISSUE THREAD

**Issue by Bowfish** [supasate/connected-react-router#108]
I changed from `react-router-redux` to `connected-react-router` When I run my app I get the error: 

No reducer provided for key "routing"

Here is my code:
reducers.js
```javascript
import { combineReducers } from 'redux'
import { routerReducer } from 'connected-react-router'

const rootReducer = combineReducers({
	routing: routerReducer
})

export default rootReducer;
```

How can I get the routerReducer that will work with  `connected-react-router`

I use:
"connected-react-router": "^4.3.0"
"react-redux": "^5.0.7",

**Comment by pronebird** [comment]
That's because you didn't read README on this repo.

```
const myReducers = {};
const rootReducer = combineReducers(myReducers);
const rootReducerWithRouter = connectRouter(history)(rootReducer);
```

**Comment by reyhansofian** [comment]
as @pronebird mentioned above, you just need to connect your router to reducer by using `connectRouter`. And then you need to adjust your implementation from `routing` to `router`

**Comment by goel1443** [comment]
provide best solution for 'No reducer provided for key'
