### ISSUE TITLE
npm WARN connected-react-router@4.3.0 requires a peer of redux@^3.6.0 but none is installed. You must install peer dependencies yourself

### ISSUE THREAD

**Issue by kostaspapas** [supasate/connected-react-router#114]
Hi,
I
npm install

and i got 

npm WARN connected-react-router@4.3.0 requires a peer of redux@^3.6.0 but none is installed. You must install peer dependencies yourself

I have installed redux@5.0.7 already. 
Do i have to do something else? 
Do I have to install peer dependencies myself?
How?

If I don't, am i going to have any problems?

thanks

**Comment by kostaspapas** [comment]
I used

 install-peerdeps 

is this ok?

**Comment by supasate** [comment]
5.0.7 would be react-redux, not redux. By the way, connected-react-router v4.4.0 lists redux 4.0 in peerDependency already.
