### ISSUE TITLE
Route is not changed

### ISSUE THREAD

**Issue by creaux** [supasate/connected-react-router#120]
Route in url is changed and action dispatched but render method is not triggered. I have also investigated about blocked route change. It doesn't help.

Is there anything particular on which I should focus? Like where to debug or what to simulate when I would like to know that integration is done properly first and then to debug for possible issue. I think I'm maybe missing something.

**Comment by ShadyXV** [comment]
Were you able to solve this issue? What was missing ? Same thing seems to happening in my app. The action is dispatched, the url changes but the route is not changed!

**Comment by creaux** [comment]
@ShadyXV issue was this https://github.com/ReactTraining/react-router/blob/v4.0.0-beta.8/packages/react-router/docs/guides/blocked-updates.md it was difficult to find it but yes it has been there.

Be aware of third party Providers. If you have many of them i suggest to try to bypass one by one and from some particular point you will see. Are you using any of these providers?
