### ISSUE TITLE
Component gets mounted twice when using with redux-saga

### ISSUE THREAD

**Issue by tlaak** [supasate/connected-react-router#126]
I have a redux-saga which yields a `put()` action with `push("/")` from `connected-react-router` as an argument in reaction to LOGIN_SUCCESSFUL action. I can see that LOCATION_CHANGE appears once in Redux dev tools, but the component which gets loaded on `/` route will be mounted twice.

I don't honestly know where to start debugging this issue, but has anyone experienced something similar?

**Comment by BaptWaels** [comment]
Yes, I'm experiencing the exact same problem. I don't know how to solve this.

**Comment by tlaak** [comment]
I made a quick and dirty demo, but looks like I'm not able to repeat the issue.

**Comment by supasate** [comment]
It should be fixed in [v6.1.0](https://github.com/supasate/connected-react-router/releases/tag/v6.1.0). Feel free to re-open this issue if the problem still exists.
