### ISSUE TITLE
Switch not updating Route when route change occurs

### ISSUE THREAD

**Issue by Sawtaytoes** [supasate/connected-react-router#130]
If `Switch` is never re-rendered, it doesn't update which causes it to not update which `Route` component it should render.

When I used react-router-redux, I had to wrap my components with react-redux's `connect` function like so:
```js
import { connect } from 'react-redux'
import { createSelector } from 'reselect'

import {
  Redirect as DisconnectedRedirect,
  Route as DisconnectedRoute,
  Switch as DisconnectedSwitch,
} from 'react-router-dom'

const mapStateToProps = (
  createSelector(
    ({ router }) => router,
    router => ({ ...router }),
  )
)

export const Redirect = connect(mapStateToProps)(DisconnectedRedirect)
export const Route = connect(mapStateToProps)(DisconnectedRoute)
export const Switch = connect(mapStateToProps)(DisconnectedSwitch)
```

While I don't have to do this with connected-react-router for most cases, I do have to do it when `Switch` is wrapped in a component that never updates, meaning, it never causes `Switch` to re-render.

**If I use the `Switch` component from my previous implementation, it works fine.**

Example to reproduce:
```js
import PropTypes from 'prop-types'
import { Component } from 'react'

export class NeverRerender extends Component {
  static propTypes = {
    children: PropTypes.node.isRequired,
  }

  shouldComponentUpdate() {
    return false
  }

  render() {
    return this.props.children
  }
}

export default NeverRerender
```

Wrap `Switch` in this component. It will not update on route changes.

For example:
```js
<NeverRerender>
  <Switch>
    <Route
      component={LoginWidget}
      path="/login"
    />

    <Redirect to="/login" />
  </Switch>
</NeverRerender>
```

In this example, if I go to `/login`, it works fine. If I go to `/`, then it redirects to `/login`, but then the LoginWidget never loads because `Switch` isn't re-rendered.

**Comment by djKooks** [comment]
I'm facing on similar issue. In my case, it is not rendering component by changing path with `replace` in redux action.

**Comment by Sawtaytoes** [comment]
Does yours work with the solution I provided which wraps them in `connect`?

**Comment by djKooks** [comment]
@Sawtaytoes oh, no. It seems my problem is bit different with yours...

**Comment by thereapman** [comment]
Just faced the same issue.

The solution seems to be to just map the location to your props.

```
export default connect((state) => {
    return {
        location: state.router.location.pathname
    }
})(App);
```

`App` then can include `Switch` and `Route` and will be rerenderd when `state.router.location.pathname` changes

**Comment by ross-weir** [comment]
I also faced this issue. @thereapman fix worked for me.

**Comment by Sawtaytoes** [comment]
That's the same solution I presented originally. It's a workaround for an issue with connected-react-router

**Comment by goonerDp** [comment]
@thereapman , is it not affecting performance?

**Comment by thereapman** [comment]
@goonerDp not 100% sure. But basically when your location won't change the component also should not re-render. I think this is the "most-proper" reduxy way to do it.

**Comment by 3plusalpha** [comment]
I found that problem lies in the order I used `connect` with `withRouter`

**not working**
```connect(mapStateToProps))(withRouter(MyComponentWithSwitch))```

**working**
```withRouter(connect(mapStateToProps))(MyComponentWithSwitch))```

**Comment by challet** [comment]
Hum, I think I made it work without a custom *connect* by just removing the `<Router>` component from the up-tree. I know that it's in opposition with the doc, but I saw the `<ConnectedRouter>` [is already rendering it](https://github.com/supasate/connected-react-router/blob/master/src/ConnectedRouter.js#L78-L80) and it has itself [the redux connection](https://github.com/supasate/connected-react-router/blob/master/src/ConnectedRouter.js#L123). 

I'm very new to all of this, but what I think to be a strange intrication (two `<Router.Provider>` ?) of Components is removed. But on a possible side effect `<BrowserRouter>` is gone.

It still seems to work on my app. Looking forward your opinions on this.

From 
![with](https://user-images.githubusercontent.com/67459/71015098-54cbb700-20f3-11ea-95e3-1fe7001eaf32.png)
To
![without](https://user-images.githubusercontent.com/67459/71015130-61500f80-20f3-11ea-9cdb-b89877262a17.png)

**Comment by adamcaron** [comment]
As per [this SO answer](https://stackoverflow.com/questions/57635090/react-router-redirect-doesnt-change-url-in-switch): 

Changing from this:
```
    <Switch>
      <Route path="/">
        <Welcome />
      </Route>
      <Redirect to="/" />
    </Switch>
```

To this:
```
    <Switch>
      <>
        <Route path="/">
          <Welcome />
        </Route>
        <Redirect to="/" />
      </>
    </Switch>
```

... worked for me. 

I was trying to implement a basic fallback redirect for any paths not explicitly specified, so random paths like http://localhost:3000/askfjasdf would redirect to `http://localhost:3000`. For some reason adding the fragment as a top level child of `<Switch>` did the trick.

**Comment by Sawtaytoes** [comment]
It's been a long time since I last used connected-react-router. Closing because I can't verify fixes anymore.

**Comment by devil-shiva** [comment]
> 
> 
> As per [this SO answer](https://stackoverflow.com/a/57644248/1899371):
> 
> Changing from this:
> 
> ```
>     <Switch>
>       <Route path="/">
>         <Welcome />
>       </Route>
>       <Redirect to="/" />
>     </Switch>
> ```
> 
> To this:
> 
> ```
>     <Switch>
>       <>
>         <Route path="/">
>           <Welcome />
>         </Route>
>         <Redirect to="/" />
>       </>
>     </Switch>
> ```
> 
> ... worked for me.
> 
> I was trying to implement a basic fallback redirect for any paths not explicitly specified, so random paths like http://localhost:3000/askfjasdf would redirect to `http://localhost:3000`. For some reason adding the fragment as a top level child of `<Switch>` did the trick.

Worked for me ,
Thanks
