### ISSUE TITLE
[Performance]: Redux state is re-created on EVERY action

### ISSUE THREAD

**Issue by sgal** [supasate/connected-react-router#133]
Due to the way router reducer is [implemented](https://github.com/supasate/connected-react-router/blob/master/src/reducer.js#L35) it changes the reference of the entire state on every action. 

This causes an unnecessary update (or rather re-calculation of `mapStateToProps`) in all connected components.
The whole idea feels a bit of an overkill just to get the initial router state from the real history object.

I would suggest to support an alternative way to connect router reducer (without wrapper function).
The idea is following:
1. Create router reducer bound to history object to support initial state (see code below)
2. Export new `routerReducer` as a named export to inject manually (same as `react-router-redux` does it)

```
export const createRouterReducer = (history) => {
    const initialRouterState = fromJS({
        location: history.location,
        action: history.action,
    })
    
    return (state = initialRouterState, action) => {
        if (type === LOCATION_CHANGE) {
            return merge(state, payload)
        }

        return state
    }
}

// reducers.js inside client app
import {createRouterReducer} from "connected-react-router";
import {createBrowserHistory} from "history";

const history = createBrowserHistory();
const routerReducer = createRouterReducer(history);

const rootReducer = combineReducers({
    ...clientReducers,
    router: routerReducer
});
```

This should also solve #104. I'm ready to send a PR if you like the idea @supasate.

**Comment by ee0pdt** [comment]
I like this proposed solution to this problem and to #132 

I'd be happy to see a PR for this

**Comment by ee0pdt** [comment]
Could we combine this solution with this PR? https://github.com/supasate/connected-react-router/pull/140

**Comment by claramunt** [comment]
some news?
