### ISSUE TITLE
LOCATION_CHANGE action is triggered on page load

### ISSUE THREAD

**Issue by stingrayfunk** [supasate/connected-react-router#144]
```
  "connected-react-router": "^4.4.1",
  "history": "^4.7.2",
  "react": "^16.4.1",
  "react-dom": "^16.4.1",
  "react-redux": "^5.0.7",
  "react-router": "^4.3.1",
  "react-router-config": "^1.0.0-beta.4",
  "react-router-dom": "^4.3.1",
```

This might come from my limited understanding of how React Router works, but...

I have a React/React Router/Redux app which renders on the server and client. However, on page load, the React Router `LOCATION_CHANGE` action is dispatched. I only want this action to be dispatched when the user explicitly routes on the client-side, not on page load. The reason being I have a Redux middleware method fetching data when the location changes during client-side routing. I don't want this method fetching data on initial page load as the data is already there.

How can I prevent `LOCATION_CHANGE` dispatching on page load? Is this a bug or intentional functionality?

**Comment by supasate** [comment]
I just realized that it was dispatched because I didn't provide the history object to set the initial router state [in the past](https://github.com/supasate/connected-react-router/blob/f84b6aa4405f27086d54cec6ff2c2fa003716d49/src/reducer.js), so, I dispatched it to set the initial router state. We don't need it now :).

**Comment by supasate** [comment]
After searching through the history of changes, I found that it was intentionally added back in #96. I think the reason makes sense to make it more compatible with `react-router-redux` and the browser actually fires a `POP` event on page load, so, it makes sense to fire the `LOCATION_CHANGE` action too.

**Comment by vtronxy** [comment]
> After searching through the history of changes, I found that it was intentionally added back in #96. I think the reason makes sense to make it more compatible with `react-router-redux` and the browser actually fires a `POP` event on page load, so, it makes sense to fire the `LOCATION_CHANGE` action too. I'm reverting it back.

「browser actually fires a `POP` event on page load」My local test in chrome89 did not verify this conclusion, I can never get the document description of this feature
