### ISSUE TITLE
Typescript definition exports RouterActionType enum where it does not exists as a value

### ISSUE THREAD

**Issue by Ailrun** [supasate/connected-react-router#155]
## Description
In TypeScript, `enum` can be used as a value, so if library exports type definition including `enum`, one would expect there is a corresponding exported value.
However, for `RouterActionType`, that's not the case, more specifically, there is no named-export whose name is `RouterActionType`.

## Possible solution
Change `RouterActionType` into normal union type, or add corresponding value in a JS file.

**Comment by Ailrun** [comment]
Oh, it looks so. Could you close this after that one is released?

**Comment by supasate** [comment]
Released in 5.0.0! (Beware of the breaking change. Please see the release note https://github.com/supasate/connected-react-router/releases/tag/v5.0.0)
