### ISSUE TITLE
Expose `onLocationChanged` action

### ISSUE THREAD

**Issue by willdurand** [supasate/connected-react-router#158]
Hi,

in some test cases, I would need to use the `onLocationChanged()` action and not the actions reacting to the `history` events. Would it be possible to expose this action somehow? Or are there any (known) issues about exposing it?

I don't like the idea of maintaining a copy of this action because it can get out of sync.

Thanks!

**Comment by supasate** [comment]
I expose it in v6.2.0.

**Comment by willdurand** [comment]
Thanks!
