### ISSUE TITLE
Rendering issue when changing the URL

### ISSUE THREAD

**Issue by kurt-hardy** [supasate/connected-react-router#161]
### Summary
Dispatching a push from a connected component does not work.

### Test Case
https://github.com/kurt-hardy/react-router-redux-issue

### Expected Behavior
Should render the correct component

### Actual Behavior
Nothing is rendered. Notice that the URL changes and if you open up redux dev tools and you will see the location change being dispatched

**Comment by fbove** [comment]
Same is happening inside a saga, doing: `yield put(push('/home'))` just changes the URL, but it does not render the component.

My config is the one from react-boilerplate plus this pr `https://github.com/react-boilerplate/react-boilerplate/pull/2375/files`.

**Comment by kurt-hardy** [comment]
This was my own mistake, I had an uppercase C when passing the component to the `Route`

`<Route path="/page-1" Component={Page1} />`

Whats your issue?
