### ISSUE TITLE
Push from a redux-observable epic - route doesn't load

### ISSUE THREAD

**Issue by darbio** [supasate/connected-react-router#166]
I am using `redux-observable`, to initiate a `push` from the epic.

Epic.ts:
```
import * as constants from '../constants';

import { map } from 'rxjs/operators';
import { Epic, ofType } from 'redux-observable';

import { push } from 'connected-react-router';

export const userLoginSuccessEpic: Epic<any> = ($action, $state) => {
  return $action.pipe(
    ofType(constants.USER_LOGIN_SUCCEEDED),
    map(() => push(`/2`))
  );
};
```

The push appears to be kind of working - the browser location is updated - however the page does not navigate to the component for the route.

How do I make the routing work?

**Comment by darbio** [comment]
This could be the same as https://github.com/supasate/connected-react-router/issues/159

**Comment by darbio** [comment]
Problem solved. My issue was that my `history` const was not being shared between my component and my store. Exporting `history` from the store and importing it into my routing component worked.

**Comment by Galya-IT** [comment]
@darbio , would you please give me more info on how you solved the problem. I have a similar one. I've created a [Stackoverflow question](https://stackoverflow.com/questions/53227446/push-from-connected-react-router-used-in-redux-observable-epic-doesnt-chang) with the details.
