### ISSUE TITLE
Cryptic error when using incorrect reducer key (e.g. "routing" instead of "router")

### ISSUE THREAD

**Issue by mattvague** [supasate/connected-react-router#174]
I kept getting this error until I realized that connected-react-router requires that `connectRouter()` be mounted under "router", whereas mine was under "routing".

Not knowing the history behind this I probably shouldn't comment, but to be honest it doesn't seem like the best design decision to impose this on peoples apps, at the very least could we throw a nice and helpful error when this happens?

![image](https://user-images.githubusercontent.com/64985/48005587-cd370a80-e0e1-11e8-8280-56c3cac9e457.png)

**Comment by supasate** [comment]
You're right. The reducer key must be `router`. I updated the readme to emphasis this.

The history is that, in the previous version, I automatically created the `router` key. However, in v5, we need to export the router reducer to make it compatible with other libraries, but, internally, we still look for the `router` key. (Code pointer - https://github.com/supasate/connected-react-router/blob/master/src/ConnectedRouter.js#L24-L29)

Some ideas (I'm happy to accept PRs)
Short term solution - handle the error with a helpful message.
Long term solution - may allow configurable router reducer key.

**Comment by mattvague** [comment]
Ah ok, makes sense. Let's do both ideas 👍 I'll submit a PR for the short term and we can keep the convo open on the long term

**Comment by mattvague** [comment]
@supasate PR'd!
