### ISSUE TITLE
Calling push on Redux Actions and LOCATION_CHANGED not called

### ISSUE THREAD

**Issue by brenoos** [supasate/connected-react-router#177]
Hello.

I have a redux action who made an Axios call, I want to push if the request get sucess, I made this:

```
import axios from 'axios'
import { push } from 'connected-react-router'

export const DATA_FETCHED = 'DATA_FETCHED'

 export const getData = () => {
    return (dispatch) => {
        axios.get("http://myurl")
            .then(resp => {
                dispatch([
                    push(`/example/path/123`),
                    {
                        type: DATA_FETCHED,
                        payload: resp
                    }
                ])
            })
            .catch(e => {
                toastr.error('Error', "not found")
            })
    }
} 
```

The action completes, I get the data, and the URL changes, but the LOCATION_CHANGE and the router state stay the same.

Can somebody help me?

**Comment by Absvep** [comment]
Same problem here. I use react-boilerplate (https://github.com/react-boilerplate/react-boilerplate) and do like this in redux-saga: 

```
function* loginFlow(username, password) {
  let apiResponse;
  try {
    apiResponse = yield call(loginApi, username, password);
    yield put(push('/newpage'));
  } catch (error) {
    // error? send it to redux
    yield put({ type: LOGIN_ERROR, error });
  } finally {
    if (yield cancelled()) {
      yield put(replace('/login'));
    }
  }
  return apiResponse;
}
```
I see that action completes in redux devtools and url changes, but the page is blank. So I need to manually click in search bar to go to new location.

**Comment by Absvep** [comment]
@brenoos What if you do 
`export default withRouter(compose(withConnect)(App))
instead of
`export default compose(withConnect)(App)
`
For me it seem to work, but I get a cancel action in some way in my saga, 
`yield cancelled()`

**Comment by brenoos** [comment]
Guys I solved in another way (not sure if its a good practice):

```
import axios from 'axios'
import { push } from 'connected-react-router'

import { LOCATION_CHANGE } from 'connected-react-router'
export const DATA_FETCHED = 'DATA_FETCHED'



export const getData = () => {
    return (dispatch, getState) => {
        let routerState = getState().router
        axios.get("http://myurl")
            .then(resp => {
                dispatch({
                    type: DATA_FETCHED,
                    payload: resp
                })
                    dispatch({
                        type: LOCATION_CHANGE,
                        payload: { 
                            location: {
                                pathname: `/example/path/123`, 
                                search: routerState.location.search,
                                hash: routerState.location.hash
                            }, 
                            action: "PUSH" 
                        }
                    })
            })
            .catch(e => {
                toastr.error('Erro', "Fundo ou Período selecionado não encontrado")
            })
```

It's working for me

**Comment by Absvep** [comment]
Ok great, but you asked for connected-react-router solution :) Maybe someone from this github can answer what the correct solution is? :)

**Comment by brenoos** [comment]
I don't understand why you said: "but you asked for connected-react-router solution". I'm using a resource from connected-react-router, I imported de const LOCATION_CHANGE and calling it, it call the locationChange action in the  connected-react-router.

Sorry about my bad English =/

**Comment by Absvep** [comment]
@brenoos I changed my writing, I wrote wrong meaning :) See now.

**Comment by brenoos** [comment]
Know I See =)

Thanks for the help

Will stay opened for wait the answer if this is a good practice

**Comment by denyo** [comment]
@brenoos your suggestion works but it's not the right way. 
Most likely something is wrong with `routerMiddleware(browserHistory)` within `configureStore`, your `rootReducer`'s `router: connectRouter(history)` or your markup:
```
<Provider store={store}>
    <ConnectedRouter history={browserHistory}>
        <App />
    </ConnectedRouter>
</Provider>
```

**Comment by brenoos** [comment]
Helloy @denyo 

My store and reducers was OK, all other functions is working correctly.

But I wil return to this project later and try to use ` withRouter ` first in my decorator

**Comment by zedwang** [comment]
Hi,the docs maybe help you. https://reacttraining.com/react-router/web/guides/redux-integration

**Comment by brenoos** [comment]
Thanks @zedwang I will try this later, for now I will keep the other solution, thanks
