### ISSUE TITLE
Resetting state in v5.0.1

### ISSUE THREAD

**Issue by jjdp** [supasate/connected-react-router#178]
How do you reset state now since `connectRouter` is passed inside `combineReducer`  and a history object is passed when creating the root reducer?

Previous way:

```
const appReducer = combineReducers({
  general: GeneralReducer
});

const rootReducer = (state, action) => {
  if(action.type == 'RESET') {}

  return appReducer(state, action);
};

export default rootReducer;
```

**Comment by svenadlung** [comment]
I am facing the same problem :(

**Comment by svenadlung** [comment]
Perfect, thx @sgal !

**Comment by michaelegregious** [comment]
Hey folks, If anyone else comes across this issue, and is still having problems (specifically receiving the error `Uncaught Could not find router reducer in state tree, it must be mounted under "router"`), I fixed it by following @sgal's suggestion but **not setting anything** for `initialState.router.`

Once I removed `initialState = { ~~router: {}~~ }` everything is working fine.
