### ISSUE TITLE
Step 1: Create a history object

### ISSUE THREAD

**Issue by HollyJHuber** [supasate/connected-react-router#185]
In the examples, the history object is created in App.js using prop-types.

`App.propTypes = {
  history: PropTypes.object,
}`

Is it okay to create a history object this way? 

`import createHistory from 'history/createBrowserHistory'`
 
`const history = createHistory()`

Thanks!!

**Comment by sgal** [comment]
@HollyJHuber Actually, in the examples the `history` is passed to `App.js` as a prop, but it's not created there. Instead, it is created in the `index.js` file which is an entrypoint of the app. Check https://github.com/supasate/connected-react-router/blob/master/examples/basic/src/index.js#L11

Good luck!

**Comment by HollyJHuber** [comment]
Thank you @sgal !
