### ISSUE TITLE
Example for Redux Observable

### ISSUE THREAD

**Issue by steadylearner** [supasate/connected-react-router#187]
I found that there was no Redux Observable example for this package yet. So I gave some time to figure out how to make it to work.

I corrected a little bit working code example from my project. First I thought that I can use store.dispatch inside redux observable but the redux observable maintainers deprecated use of store api.

So I experimented some codes and found that I can use apis of this package when I use them inside mergeMap inside other action creators.

I hope that the example below will be useful for future users.

The most important part is to use mergeMap as I wrote above.

```JavaScript
mergeMap(response => {
    return of(apiSearchFulfilled(response), push(`/path/${response.payload}`));
})
```

**EXAMPLE**

```JavaScript
import {
    switchMap,
    mergeMap,
    catchError,
    takeUntil,
    distinctUntilChanged,
    throttleTime,
} from "rxjs/operators";
import { ajax } from "rxjs/ajax";
import { of } from "rxjs";
import { ofType } from "redux-observable";

import { push } from "connected-react-router";

export const apiSearch = input => ({
    type: "API_SEARCH",
    payload: input,
});

const apiSearchFulfilled = ({ items }) => ({
    type: "API_SEARCH_FULFILLED",
    payload: items,
});

const apiSearchRejected = payload => ({
    type: "API_SEARCH_REJECTED",
    payload,
    error: true,
});

export const apiSearchCancelled = () => ({ type: "API_SEARCH_CANCELLED" });

// Observable here already
export const searchEpicWithConnectedReactRouter = (action$, state$) => (action$.pipe(
    ofType("API_SEARCH"),
    switchMap(action => ajax.getJSON(`www.example.com${action.payload}`).pipe(
        distinctUntilChanged(),
        throttleTime(1000),
        mergeMap(response => {
            return of(apiSearchFulfilled(response), push(`/path/${response.payload}`));
        }),
        takeUntil(action$.pipe(
            ofType("API_SEARCH_CANCELLED"),
        )),
        catchError(error => {
            return of(apiSearchRejected(error.xhr.response || "DEFAULT ERROR MESSAGE."));
        }),
    )),
));

```

It was not so easy to understand what to do at the first moment. I hope you include more simplified version of this example to this repository.

**Comment by rodrigobacelli** [comment]
There's this [migration to v1.0.0](https://redux-observable.js.org/MIGRATION.html) that uses mergeMap. RxJs [mergeMap](https://www.learnrxjs.io/operators/transformation/mergemap.html) docs also provides the reason to use mergeMap instead of map there.

There's no need to add an example in this repo just for this.

**Comment by lucastschmidt** [comment]
If anyone needs an example on how to listen for a route change and perform something, like emitting another action. Be aware of the distinctUntilChanged, since, it looks like on every state change is emitted that LOCATION CHANGE event.

```
const onLocationChangedToProjectsListEpic = action$ => (
  action$.ofType(LOCATION_CHANGE_SUCCESS).pipe(
    isRoute(routes.PROJECTS),
    distinctUntilChanged(),
    withLatestFrom(
      action$.ofType(GET_PROJECTS_LIST_START).pipe(
        startWith(getFirstProjectsListStartAction()),
      ),
    ),
    tap(() => logger('Opening projects list')),
    switchMap(([, getProjectsListAction]) => (
      of(getProjectsListAction)
    )),
  )
);
```


the isRoute is just a filter, and the LOCATION_CHANGE_SUCCESS is `@@router/LOCATION_CHANGE`
