### ISSUE TITLE
Incompatible with react-router v4.4.0-beta.6

### ISSUE THREAD

**Issue by filoxo** [supasate/connected-react-router#206]
I was upgrading an older app and attempting to use connected-react-router, and encountered the following error being generated by react-router when attempting to wrap `Link`s and `Switch`es in this library's `ConnectedRouter`.

```
Error: Invariant failed: You should not use <Link> outside a <Router>
```

Repro example: https://codesandbox.io/s/ymk0787ox

I'm not familiar with how react-router previously allowed other Router implementations, but it seems that this future version no longer will. I'm also unsure whether this is an issue with connected-react-router or a regression/problem that should be fixed in react-router but I wanted to get your input. Thanks!

**Comment by filoxo** [comment]
For additional context, I have to use that version of react-router because of issues with react-router `Route`s unable to properly handle React.lazy() components. The fix (https://github.com/ReactTraining/react-router/pull/6417) for that problem was merged but a new release hasn't been made yet.

**Comment by filoxo** [comment]
Some additional info: 

- Using v4.3.1 works fine
- I found a workaround by wrapping the `ConnectedRouter` in react-router's own `BrowserRouter` seems to have worked to silence the error, but of course, isn't ideal.

**Comment by mick-feller** [comment]
i am facing the same problem...

**Comment by Louis-Chen** [comment]
same problem +1 

when i use jest test it happened

**Comment by supasate** [comment]
@filoxo I saw your codesandbox uses react-router-dom@4.4.0-beta.6, but, uses react-router@4.3.1.

![image](https://user-images.githubusercontent.com/237753/51082580-af6ecd00-1744-11e9-82c0-9840fa345e0a.png)

I created a test repo here https://github.com/supasate/test-react-router-4.4.0 and it works well by using react-router and react-router-dom v4.4.0-beta.6. I saw the error appeared if I change one of that to 4.3.1.

However, even though my repo works well on my local machine, when I imported it to Codesandbox, it shows the same error. I guess, on Codesandbox, the `Link` component may import `react-router` from a different location of the main `react-router` used in the repo, and [`Link` needs Context from react-router](https://github.com/ReactTraining/react-router/blob/v4.4.0-beta.6/packages/react-router-dom/modules/Link.js#L2), so, it may get a different context.

Please let me know if it still happens on your local machine and please provide a repo that I can clone and test on my machine.

**Comment by supasate** [comment]
Closing for now. If anyone still has this issue, feel free to add more comments and provide some minimal reproducible github repo.

**Comment by houmingjie** [comment]
https://reacttraining.com/blog/react-router-v5/#why-the-major-version-bump
