### ISSUE TITLE
In Time Travel, URL is only updated if the path changes, the search is ignored

### ISSUE THREAD

**Issue by csillag** [supasate/connected-react-router#21]
The [current version of the code] only compares the `pathname` part of the location, to detect time travel debugging, but it totally ignores the `search` part of the location. (ie. ?foo=bar)

Therefore, if during time travel, the only changes in the URL happen in the search part, the change is ignored, and the URL is not updated.

It would be nice to fix this. (One simply has to check the search part too, it's pretty much works the same way.)

**Comment by supasate** [comment]
You're right. It should check the `search` part also. I'll look into this issue this weekend (and very welcome if you'd like to make a PR).

**Comment by supasate** [comment]
@csillag Already fixed in `v2.0.0-alpha.5`.
