### ISSUE TITLE
[ts] Parameter 'state' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by ZeroCho** [supasate/connected-react-router#231]
Regarding [this commit](https://github.com/supasate/connected-react-router/commit/b7bc1ac6a5eaf43e8526ce2166a302055852af4f#diff-b52768974e6bc0faccb7d4b75b162c99), `Parameter 'state' implicitly has an 'any' type.` error happens. I think `noImplicitAny` should be applied for all `.d.ts` files. It's what DefinitelyTyped recommends.

**Comment by fwh1990** [comment]
Yeah, I got the same error.

**Comment by supasate** [comment]
Can you help fire a PR to fix this?

**Comment by supasate** [comment]
Fixed in v6.2.1.
