### ISSUE TITLE
Working with v4-alt of react-router

### ISSUE THREAD

**Issue by slightlytyler** [supasate/connected-react-router#24]
Looks like `StaticRouter` is gone, any ideas how to proceed? First time diving into v4 code base so not exactly sure what the change means in terms of required updates.

**Comment by supasate** [comment]
Yes. I'm aware of that. Currently, `v4-alt` won and became the next `v4`. I'm waiting for their new release/tag before upgrading.

**Comment by slightlytyler** [comment]
@supasate awesome, hopefully sometime this week!

**Comment by olegstepura** [comment]
I'm sorry to ask this, but I'm kid of lost (but I'm sure I'm not the only one).

1. What is the status supporting react-router@alpha atm?
2. Is currently released `react-router@4.0.0-alpha.6` the one that was the `v4-alt` version and it requires changes from `connected-react-router` side to make it work?
3. Maybe you can also make it clear if this readme is actual for next version of react router: https://github.com/ReactTraining/react-router/blob/v4/README.md

Thanks!

**Comment by supasate** [comment]
@olegstepura That's fine. The situation of react-router is confusing.
1. Now, `connected-react-router` supports `react-router@4.0.0-alpha.6` which is the the version with `Match` and `Miss`. (Read more below.) 
2. `react-router@4.0.0-alpha.6` is the version before `v4-alt` (current `v4`). It doesn't require any change to `connected-react-router`. (Read more below.)

I just noticed that, around 40 minutes ago, the `react-router` team has just released `beta` version (`Match` and `Miss` are gone). So, it's time to update this repo to handle the new version of `react-router`.

**Comment by supasate** [comment]
Now, we support the new `react-router@4.0.0-beta`! (PR #28)

Please check the `connected-react-router@4.0.0-beta.1`. If anyone finds any issue, please let me know.
