### ISSUE TITLE
(ConnectedRouter) `connect` function always re-rendering when route change 

### ISSUE THREAD

**Issue by tomzaku** [supasate/connected-react-router#242]
Same issue at [here](https://github.com/supasate/connected-react-router/issues/205), still re-rendering 

Version:
```
 "react": "16.7.0-alpha.0",
 "react-dom": "16.7.0-alpha.0",
  "react-redux": "^6.0.0",
"react-redux": "^6.0.0",
"redux": "^4.0.0",
"connected-react-router": "^6.2.1",
"react-router": "^4.3.1",
 "react-router-dom": "^4.3.1",
```
Line 24 at https://codesandbox.io/s/qx15olry2q
Swith ConnectedRouter to Router and click the button to see the different

**Comment by KvanSteijn** [comment]
I have exactly the same issue. If i am switch back to Router, the page doesn't reload.

**Comment by jancama2** [comment]
Try to use `react-router-dom@4.4.0-beta.7`. Solved the problem for me.
