### ISSUE TITLE
Webpack 2?

### ISSUE THREAD

**Issue by olegstepura** [supasate/connected-react-router#25]
Since all the stuff here is currently in non-release phase,  don't you think you can create examples with Webpack2 (which is beta as well)?

It looks like hot reloading of `App` component should become easier (less code in index.js)

**Comment by supasate** [comment]
I think other stuffs that are not directly approached by this library (`react-router` and `react-hot-loader`) will keep using the stable version. So, I hope it will make less noise for most users.

**Comment by olegstepura** [comment]
Maybe it would make sence to have it separate?

**Comment by supasate** [comment]
Good news. Webpack 2 will be out of beta soon https://medium.com/webpack/webpack-2-2-the-final-release-76c3d43bf144#.gcedwp66e.

**Comment by olegstepura** [comment]
Webpack 2 is released.

**Comment by supasate** [comment]
Already changed the example to use Webpack 2! (https://github.com/supasate/connected-react-router/commit/fb419ff529433c424238aef8851f8fcc430b6a81)
