### ISSUE TITLE
Typescript error with release 6.3.0

### ISSUE THREAD

**Issue by moimael** [supasate/connected-react-router#255]
With TypeScript 3.3.1 I get this error when using connected-react-router 6.3.0:

```
ERROR in /Development/portal/node_modules/connected-react-router/index.d.ts(64,83):
TS2371: A parameter initializer is only allowed in a function or constructor implementation.
```

**Comment by NatalyMac** [comment]
Hi, guys) I have the same issue
    "typescript": "^3.0.3",
 "connected-react-router": "^6.3.0",
and error 
ERROR in [at-loader] ./node_modules/connected-react-router/index.d.ts:64:83 
    TS2371: A parameter initializer is only allowed in a function or constructor implementation.
The error is here
---  export function onLocationChanged(location: Location, action: RouterActionType, _**isFirstRendering: boolean = false) ---**_

if i set to ignor this error everything works, but I need typescript.
How can I fix?

**Comment by belgattitude** [comment]
Same with typescrit 3.3.3.

**Comment by nikolay-borzov** [comment]
Will be fixed by https://github.com/supasate/connected-react-router/pull/253

**Comment by flq** [comment]
@natalymac what do you mean by ignoring error?

Since I was just to take the plunge into redux 6.0 territory, what’s recommended here? Reverting to a previous versuon? Waiting?
