### ISSUE TITLE
Unable to push using location-like object

### ISSUE THREAD

**Issue by sharynneazhar** [supasate/connected-react-router#257]
The react-router `push` method allows me to pass in a location-like object[1] like this: 

```
history.push({
  pathname: '/home',
  search: '?the=query',
});
```

This does not seem to be working with connected-react-router. Can someone look into this? 

[1] https://github.com/ReactTraining/history#navigation

**Comment by brianpkelley** [comment]
Did you resolve this?  Facing the same issue currently
