### ISSUE TITLE
createMatchSelector typedef string or object?

### ISSUE THREAD

**Issue by MitchWeiss** [supasate/connected-react-router#258]
There isn't much documentation on `createMatchSelector` but in other places eg #38, the parameter is an object:

`const matchSelector = createMatchSelector({ path: '/course/:id })`

The typedef added in #235 expects a string. 

I believe the typedef is incorrect. My understanding of the code is that this parameter is provided as the second parameter in react-router's `matchPath` which expects an object https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/matchPath.md

Can anyone else confirm that this typedef is incorrect?

**Comment by robchristian** [comment]
Would also like to see some documentation surface. The readme leaves me thinking this library doesn't have support for route params.

**Comment by zaverden** [comment]
Current typedef does not cover all valid usecases. https://github.com/supasate/connected-react-router/blob/f27512640e992f420935c7790cdbed746a8306e0/index.d.ts#L73-L75

The `path` argument is used a 2nd parameter for `matchPah`
https://github.com/supasate/connected-react-router/blob/d2f0bb088a12ef5e07eeeeb3a1fa0ed23deef094/src/selectors.js#L34

In the `matchPah` 2nd argument is defined as `string | string[] | RouteProps`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3e0007a3a88eca10f61fcb55d78dd66e323f24c6/types/react-router/index.d.ts#L133
