### ISSUE TITLE
isFirstRendering always false

### ISSUE THREAD

**Issue by AlexeyAbretov** [supasate/connected-react-router#259]
in actions.js the method onLocationChanged has the parameter isFirstRendering but the method onLocationChanged from ConnectedRouter.js does not send a value.

**actions.js**
export const onLocationChanged = (location, action, **isFirstRendering = false**) => ({
  type: LOCATION_CHANGE,
  payload: {
    location,
    action,
    isFirstRendering,
  }
})

**ConnectedRouter.js**
const mapDispatchToProps = dispatch => ({
    onLocationChanged: (location, action) => **dispatch(onLocationChanged(location, action))**
  })

**Comment by supasate** [comment]
What the bug does it cause?

Basically, it's intended to be false except only for the first time [here](https://github.com/supasate/connected-react-router/blob/master/src/ConnectedRouter.js#L66).

**Comment by AlexeyAbretov** [comment]
We use SSR in our apps.

We cannot determine the first LOCATION_CHANGE.

This needed to prevent get data on client because they received on server.

**Comment by ufukomer** [comment]
I don't user SSR but it is always same for me too. I've integrated connected-react-router with create-react-app.

**Comment by supasate** [comment]
@AlexeyAbretov I re-read the code again and you're right. It's obviously a bug. The 3rd argument is passed from `handleLocationChange`, but, it is not forwarded to the `onLocationChange` props. I'm merging your PR.
