### ISSUE TITLE
typescript error no exported  ReactReduxContextValue

### ISSUE THREAD

**Issue by DAlekseenko** [supasate/connected-react-router#268]
Error:(4, 12) TS2305: Module '"../@types/react-redux"' has no exported member 'ReactReduxContextValue'.
@types/react-redux: 6.0.13
connected-react-router: 6.3.2
![DeepinScreenshot_выберите-область_20190313150441](https://user-images.githubusercontent.com/16455608/54277975-44a20c80-45a2-11e9-977d-ffb0fb29d779.png)

**Comment by chasecaleb** [comment]
I can verify this. This was first introduced in [release 6.3.0](https://github.com/supasate/connected-react-router/releases/tag/v6.3.0) via #245, which bumped the version of `@types/react-redux` to `^7.0.0`.

I'm not really sure what the right way to handle this is, but I want to point out that v7 of react-redux is still in alpha as of today - check out [their releases](https://github.com/reduxjs/react-redux/releases). There also aren't any v7 builds on npm. Maybe #245 should be reverted until v7 is officially released?

In the meantime I'm personally solving this by staying on `connected-react-router@6.2.2`.

**Comment by DAlekseenko** [comment]
Мне помогло обновление до версии @ types / Reaction-redux 7.0.5!
