### ISSUE TITLE
Support for react-router 5.0.0

### ISSUE THREAD

**Issue by mikecousins** [supasate/connected-react-router#274]
Should just need a peer dependency update I think. It's a non-breaking change in react-router supposedly.

**Comment by sugarshin** [comment]
+1

**Comment by cmfcmf** [comment]
This has been fixed by #273 and released in react-router@6.4.0.

**Comment by Puspendert** [comment]
@cmfcmf you mean **connected-react-router@6.4.0**? Is it a typo by you?

**Comment by carloscuesta** [comment]
Yup, this issue should be closed, as @cmfcmf this change has landed at `6.4.0` and it's already released and published.

https://github.com/supasate/connected-react-router/releases/tag/v6.4.0
