### ISSUE TITLE
Is there any way to use this library if I am not using combineReducers()? 

### ISSUE THREAD

**Issue by endpointed** [supasate/connected-react-router#280]
I am trying to fix my redux state to be a specific structure and `combineReducers()` does not work for the said purpose.

The documentation lacks any information as to why `combineReducers()` must be used, but it almost feels like either I use `combineReducers()` or I cannot use this library.

Is there any workaround?

**Comment by patricklafrance** [comment]
Yes, you can. I dont use `combineReducers` in my projects and connected-react-router still works fine.

```
const middlewares = [
    routerMiddleware(history)
];

const enhancers = applyMiddleware(...middlewares);

const store = createReduxStore(rootReducer, enhancers);
```
