### ISSUE TITLE
Outdated peer dep react-redux

### ISSUE THREAD

**Issue by Levino** [supasate/connected-react-router#285]
https://github.com/supasate/connected-react-router/blob/a8e92e6ee160b07876819219a8393816c9a000c4/package.json#L38

I guess this is now 7.0.0, right?

**Comment by gautier-lefebvre** [comment]
Latest `react-redux` version is `6.0.1` 😄.

**Comment by Levino** [comment]
Sorry, I got confused and thought that react-redux version 6 was used as a dev dep. Actually it is only the ts definitions that are in version 7, which is kinda wrong, but not really an issue I guess. https://github.com/supasate/connected-react-router/blob/a8e92e6ee160b07876819219a8393816c9a000c4/package.json#L49

Closing.
