### ISSUE TITLE
Un-compatibility with react-router@^5.0.0

### ISSUE THREAD

**Issue by genexu** [supasate/connected-react-router#288]
I just try on react-router@^5.0.0 with connected-react-router@^6.3.2, it seem to be un-compatibility. <ConnectedRouter /> didn't pass router store to child component. 

After downgrade react-router and react-router-dom pacakge version (@^4.3.4) everything working fine again.

![螢幕快照 2019-04-01 下午6 21 08](https://user-images.githubusercontent.com/20200209/55320952-074ae380-54ab-11e9-9df7-591593df851a.png)

I'm trying to fix this issue and PR (If i'm not too busy), looking for any reply.

_Originally posted by @genexu in https://github.com/supasate/connected-react-router/pull/273#issuecomment-478523354_

**Comment by bugzpodder** [comment]
When I ran into this, it was because react router and react router dom did not have the exact same version.  Double check you did.

**Comment by thehig** [comment]
I'm having a similar error. I resolved the `You should not use <X> outside a <Router>` for `<Route>`, `<Switch>`, `<Redirect>` by changing my imports from `react-router-dom` to `react-router`, however I can't figure out how to resolve the error for `<Link>`s

### Versions:

```
"connected-react-router": "^6.3.2",
"react": "^16.8.6",
"react-dom": "^16.8.6",
"react-redux": "^7.0.1",
"react-router": "^5.0.0",
"react-router-dom": "^5.0.0",
"redux": "^4.0.1",
```

**Comment by bugzpodder** [comment]
Can you do a yarn why or npm version to check the version of react-router and react-router-dom? Make sure not multiple version is installed.  You can also remove node_modules and reinstall.

**Comment by thehig** [comment]
They're definitely the same version. Just did a clear out and reinstall of node_modules and am having the same error

![image](https://user-images.githubusercontent.com/96122/55950249-5a136080-5c4c-11e9-9078-fc5df20fbe01.png)

**Comment by thehig** [comment]
I can't fully say what fixed it, but I deleted my package-lock.json and reinstalled (fixed some new bugs that were introduced) but then got this working.

**Comment by rpedela** [comment]
I ran into the same error for ```<Link>```, and what worked for @thehig also worked for me.

**Comment by EdmundMai** [comment]
i too had to delete package-lock and reinstall to get it to work
