### ISSUE TITLE
Allow to use specific Router component 

### ISSUE THREAD

**Issue by SuperCiacho** [supasate/connected-react-router#291]
I would like to use customized user confirmation popup.
Currently neither Router or ConnectedRouter component doesn't allow to that.
It would be nice to have possibility of using specific implementation of Router (MemoryRouter, BrowserRouter, etc.) with certain configuration or have **getUserConfirmation** property.

**Comment by fiskus-naive** [comment]
Try to use `createMemoryHistory` instead of `createBrowserHistory` https://github.com/ReactTraining/history/blob/master/docs/GettingStarted.md
