### ISSUE TITLE
Move immutable.js to peer dependencies

### ISSUE THREAD

**Issue by gugu** [supasate/connected-react-router#296]
Currently connected-react-router requires immutable v3 as dependency. If somebody uses immutable v4, both v3 and v4 are included in the bundle

**Comment by fafamx** [comment]
And also it does so by including immutable.js instead of immutable.es.js which cause not supporting tree shaking at all.

**Comment by veeramarni** [comment]
Or just use https://github.com/immerjs/immer instead of depending on immutable.js

**Comment by philipnilsson** [comment]
How come this library even has a dependency on immutable? I'd like to use this library, but do I need to ship essentially all of immutable.js just for that? Should I just look elsewhere if want something with a low bundle-size impact?

**Comment by gugu** [comment]
> How come this library even has a dependency on immutable? I'd like to use this library, but do I need to ship essentially all of immutable.js just for that? Should I just look elsewhere if want something with a low bundle-size impact?
> 
> Or will immutable only end up in my bundle if I include something specific?

Immutable will be included only if you will import `connected-react-router/immutable`

**Comment by jackmellis** [comment]
Hi, this is a big problem for us too. Because this library installs immutable, then another library that has it as an optional dependency goes "nice I guess we're using immutable now then?" and pulls the entire library into the webpack bundle.

If you could make this an optional dependency that would be amazing.

^ the "other" library is redux-form by the way

**Comment by limpbrains** [comment]
> > How come this library even has a dependency on immutable? I'd like to use this library, but do I need to ship essentially all of immutable.js just for that? Should I just look elsewhere if want something with a low bundle-size impact?
> > Or will immutable only end up in my bundle if I include something specific?
> 
> Immutable will be included only if you will import `connected-react-router/immutable`

I only import { ConnectedRouter, connectRouter, push, routerMiddleware } from 'connected-react-router' but I have immutable/dist in my bundle.

connected-react-router is the only lib which has immutable in deps in my project

**Comment by gugu** [comment]
it downloads the library, but the library is not added into your bundle unless you load immutable version of this module

**Comment by limpbrains** [comment]
> it downloads the library, but the library is not added into your bundle unless you load immutable version of this module

Sorry, you are right. It was redux-form

**Comment by jackmellis** [comment]
My dirty workaround for this btw is to add this script to my package.json:
```json
"postinstall": "rm -rf node_modules/immutable",
```
:laughing:

**Comment by gugu** [comment]
> My dirty workaround for this btw is to add this script to my package.json:
> 
> ```json
> "postinstall": "rm -rf node_modules/immutable",
> ```
> 
> 😆

This is kind of useless. If you don't user connected-react-router/immutable it will not be loaded in your bundle. If you use it - your build will be broken

**Comment by jackmellis** [comment]
To clarify, the workaround was for when using connected-react-router as well as redux-form (which dumps immutable in your bundle of it exists in your nose modules)

**Comment by maxmalov** [comment]
For the reference https://github.com/redux-form/redux-form/issues/4519

**Comment by supasate** [comment]
Fixed in #390.
