### ISSUE TITLE
router.location is null on pageload

### ISSUE THREAD

**Issue by davekiss** [supasate/connected-react-router#3]
@supasate Thanks for your effort on this project, giving it a whirl to see how it goes.

I'm unsure if this is the intended behavior, but it seems that `router.location` is `null` in state until I actually navigate with a Link helper, at which point it populates with the expected data.

Is there a way to ensure this data is present on pageload from the initial route, or am I doing something wrong?

Cheers!

**Comment by supasate** [comment]
Thank you for reporting this issue. I will fix it.

**Comment by supasate** [comment]
@davekiss Already fixed in v1.0.0-alpha5! Let's try and let me know.
