### ISSUE TITLE
Is this a replacement for the ControlledRouter component?

### ISSUE THREAD

**Issue by olegstepura** [supasate/connected-react-router#30]
Hi!
I've just [found this](https://github.com/ReactTraining/react-router-addons-controlled) digging react router repos. I didn't inspect it too deeply but for me it seems like it's almost the same as this package. 

Is this different? Or will the `ControlledRouter` replace need for this package when it's ready?

Thanks!

**Comment by supasate** [comment]
Short answer is yes. This is a replacement for the `ControlledRouter`.

AFAIK `ControlledRouter` uses two-way data flow but `ConnectedRouter` uses one-way data flow (follows the React/Flux way) and simplifies the logic inside. 

This project was originated from the [discussion](https://github.com/reactjs/react-router-redux/pull/460#issuecomment-260999726) by @lourd and @timdorr.

**Comment by olegstepura** [comment]
Thanks for the answer and the project =) 
[The say it's Redux implementation](https://github.com/ReactTraining/react-router/tree/v4#what-about-redux), it was strange if it's two-way data flow. But the discussion you mentioned makes it clear what the difference is.

BTW, Did you fix the time travel feature?

**Comment by supasate** [comment]
Yes. It works!
