### ISSUE TITLE
Location state absent in LOCATION_CHANGE action

### ISSUE THREAD

**Issue by fzaninotto** [supasate/connected-react-router#301]
React-router uses history's `location` object:

>The `location` object implements a subset of [the `window.location` interface](https://developer.mozilla.org/en-US/docs/Web/API/Location), including:
>
>- `location.pathname` - The path of the URL
>- `location.search` - The URL query string
>- `location.hash` - The URL hash fragment
>
>Locations may also have the following properties:
>
>- `location.state` - Some extra state for this location that does not reside in the URL (supported in `createBrowserHistory` and `createMemoryHistory`)
>- `location.key` - A unique string representing this location (supported in `createBrowserHistory` and `createMemoryHistory`)

(see https://github.com/ReactTraining/history#listening)

connected-react-router only passes `pathname`, `search` and `hash` fields to the `LOCATION_CHANGE` action, and ignores the `state` and `key` fields.

https://github.com/supasate/connected-react-router/blob/37e90d7a55717046d4265f5832d3f9c8356e7db8/src/ConnectedRouter.js#L28-L49

As a consequence, a link using location state like this:

```jsx
<Link to={{ pathname: '/hello', state: { foo: 'bar' } }}>Hello</Link>
```

Is translated by connected-react-router as the following action:

```js
{
  type: '@@router/LOCATION_CHANGE',
  payload: {
    location: {
      pathname: '/hello',
      search: '',
      hash: ''
    },
    action: 'POP',
    isFirstRendering: false
  }
}
```

Notice the missing `state` key in the `location`.

As a consequence, reducers can't use the value passed in the `state`.

Note that [this was properly handled by `react-router-redux`](https://github.com/ReactTraining/react-router/blob/v4.3.1/packages/react-router-redux/modules/ConnectedRouter.js).

**Comment by nefil1m** [comment]
@supasate any update on this? It looks like the fix is pretty simple and I'm not sure why the issue is stale for so long

**Comment by rob2d** [comment]
Update? right now requiring a bit of over-engineering to use route-params within reducers or actions which isn't great.

**Comment by digicontributer** [comment]
Please review this.
