### ISSUE TITLE
Basename not working

### ISSUE THREAD

**Issue by lpeliberty** [supasate/connected-react-router#306]
I'm using connected-react-router with my react redux app.
I need server side rendering and client side rendering (I'm using a react component in a symfony twig template via limenius react bundle).

My probleme is that i cannot use basename properly. I have a locale isocode in my URL (www.localhost.com/fr/mypage)

If i declare a basename '/fr/' in history:
```
<Route exact path={`/${isocode}/checkout/customize`} component={Customize} />
```
works ! 

... but I want this : 
```
<Route exact path="checkout/customize" component={Customize} />
```

and it does not work !

What i have in my app.js: 
```js
export const App = () => {
  const store = ReactOnRails.getStore('CustomizeStore');
  const state = store.getState();
  const { isocode } = state.general.data.locale;
  const history = createHistory({
    basename: `/${isocode}/`,
    initialEntries: [state.router.location.pathname],
  });

  return (
    <Provider store={store}>
      <ConnectedRouter history={history}>
        <Switch>
          <Route exact path={`/${isocode}/checkout/customize`} component={Customize} />
        </Switch>
      </ConnectedRouter>
    </Provider>
  );
};
```

and in my store.js
```js
export const createHistory = historyConfig =>
  isServer ? createMemoryHistory(historyConfig) : createBrowserHistory();

export default (props, context) => {
  const { baseURL } = props.general.data.api;
  const { isocode } = props.general.data.locale;
  const history = createHistory({ basename: `/${isocode}/`, initialEntries: [context.pathname] });

  return createStore(
    reducers(history),
    { ...props },
    composeEnhancers(
      applyMiddleware(thunk, routerMiddleware(history)),
    ),
  );
};
```

________________________________________________________________

What i expect in my app.js: 
```js
<Provider store={store}>
  <ConnectedRouter history={history}>
    <Switch>
      <Route exact path="checkout/customize" component={Customize} />
    </Switch>
  </ConnectedRouter>
</Provider>
```

I've read that the basename for "browserRouter" and "staticRouter" provided by react-router should be declared in history props of ConnectRouter component.

What I'm doing wrong ? Is connect-react-router a good choice for my redux ssr application or should i use react-router ? (I'm using immutable.js and i want to implement hot-reloading if possible =)

A big thanks !

**Comment by lpeliberty** [comment]
I don't find why it's not working, I think there is a bug with basename. Does someone have an example that works, I'm doing something wrong ? It would be great to don't have to prefix all routes with isocode !

**Comment by lpeliberty** [comment]
I'm still on the bug, can't find from where it's coming...
Btw, does someone know approximatly when this lib will support redux 7 ? 

Thx team !

**Comment by rakeshpai** [comment]
Did you resolve this issue? Looks like basename doesn't exist on the router component.

**Comment by lpeliberty** [comment]
No, I've posted a suggestion on history repo : [https://github.com/ReactTraining/history/issues/707](https://github.com/ReactTraining/history/issues/707).
The problem is that History team says we are not supposed to use memoryHistory on server. So they does not provide a basename because we should control URL on our non'browser application. The only way I've fond is to fork history repo and add basename on createMemoryHistory (super easy to do).

I'm sure there's a problem for ssr, one of history or connected-react-router have to evolve in this way !
