### ISSUE TITLE
Хуйня не рабочая

### ISSUE THREAD

**Issue by mosario** [supasate/connected-react-router#308]
Сделал все строго по мануалу, пуш не работает, клики не работают как будто в атрибутах проставлен точный путь

**Comment by gugu** [comment]
Руки не из плеч растут просто

I am disappointed by these people, who instead of supporting modules try to offend authors.

@mosario it definitely works for 10 000+ people. If you need help, you need to provide more details

**Comment by zalishchuk** [comment]
@gugu just close the pointless issue,  make him learn how to behave in the community 🤷‍♂

**Comment by gugu** [comment]
I have no access to do this. I hope someone who has an access can close this shame

**Comment by steppefox** [comment]
@supasate Could you close that issue?
