### ISSUE TITLE
Use react-router or react-router-dom?

### ISSUE THREAD

**Issue by Zrna** [supasate/connected-react-router#323]
Should I use **react-router** of **react-router-dom**?

I started my project using react-router-dom.

The [step 3](https://github.com/supasate/connected-react-router#step-3) in the documentation states:
   `import { Route, Switch } from 'react-router' // react-router v4/v5`

Is there any difference if I use:
  `import { Route, Switch } from 'react-router-dom';` ?

**Comment by 360ammar** [comment]
`react-router` has all the common components for `react-router-dom` and `react-router-native`. 
You should use `react-router-dom` if you are building for the web and it should have everything you need as it also exports the common components you'll need. 
If you're using React Native, use `react-router-native` should have everything you need for the same reason.
