### ISSUE TITLE
connected-react-router completely eliminates component local state?

### ISSUE THREAD

**Issue by zurcacielos** [supasate/connected-react-router#346]
is it by design that class and functional components can't hold local state upon navigation?

If somebody can confirm it I can do a pull request on the docs, or let me know if I'm missing something and component local state can be hold between Link router navigation. 

Thanks

**Comment by danielnehrig** [comment]
i've been having similar problems
add a console.log to your componentWillUnmount() on the component u think will reset its state
pretty sure its just ur component being unmounted and then remounted

**Comment by danielnehrig** [comment]
check if u use a anonymous function in your render method

**Comment by zurcacielos** [comment]
Not having the problem now. Will check if I have it again. Thanks
