### ISSUE TITLE
Build may be broken in 6.5.2

### ISSUE THREAD

**Issue by sgrimard** [supasate/connected-react-router#352]
Greetings,

It seems the build does not work anymore in 6.5.2. If I am not mistaken, the problem might go back to commit 4781828c0254a58d7905c3d2d8cdd31eb5dc59cc and the migration to webpack 4 and as such be present since 6.3.2 (i did not do a bissect to confirm it)

The problem shows up when doing a clean rebuild (right after checkout or after a git clean).
The files in the umd directory that were once generated during build are not output anymore and are instead used as source in the webpack step.

Steps to reproduce:
- do a clean checkout of the repository
- yarn install
- yarn build

Can you confirm this behavior or is something wrong on my end ?

**Comment by eordano** [comment]
Confirmed on MacOS Catalina.

**Comment by supasate** [comment]
Fixed.
