### ISSUE TITLE
TS: location.query is not defined in RouterState.location interface

### ISSUE THREAD

**Issue by antokara** [supasate/connected-react-router#381]
As described in https://github.com/supasate/connected-react-router/pull/356,
the `query` prop was added to the `location` object but the typescript typings do not include it.

`interface RouterState`
https://github.com/supasate/connected-react-router/blob/master/index.d.ts#L25

now, technically, this is a problem with the `history` package's typings
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/history/index.d.ts#L29
which you use in your package.

I guess the solution might be to fix the `history` typings to include the `query` prop or
augment it to include the missing prop or even, completely provide your own `location` type.

Because I am not sure which approach you prefer to take, I didn't open an issue on the `history` repository or create a PR with a fix...

**Comment by alexbaumgertner** [comment]
The same problem.
