### ISSUE TITLE
[documentation] Is <Router> required to be added ?

### ISSUE THREAD

**Issue by challet** [supasate/connected-react-router#384]
Hello, 

The documentation, on step 3 wrote : 
```
<Provider store={store}>
    <ConnectedRouter history={history}> { /* place ConnectedRouter under Provider */ }
      <> { /* your usual react-router v4/v5 routing */ }
```
Imho, it is not clear what `<>` means : is it to be replaced by a `<Router>` component ? That's what I thought (see #130).

But, looking at the code, this component is already rendered as a child of `<ConnectedRouter>` https://github.com/supasate/connected-react-router/blob/master/src/ConnectedRouter.js#L78-L80

So maybe it's not meant to be replaced by a component, after all.

**Comment by mikew** [comment]
`<>` is a (rather confusing) shorthand for `<React.Fragment>`.
