### ISSUE TITLE
Plan to support SSR

### ISSUE THREAD

**Issue by Neophy7e** [supasate/connected-react-router#39]
Do there is any plan to support server side rendering  ?

**Comment by supasate** [comment]
Yes. I'm also thinking about it. Hope that it would be done soon.

Anyway, PR is also welcome :).

**Comment by guywald1** [comment]
+1

**Comment by nickwaelkens** [comment]
Would love to get this too! Keep up the good work @supasate!

**Comment by paradoxxxzero** [comment]
Would be great!

For now I'm using the following hack, I get the `StaticRouter` history like this:
```javascript
  const staticRouter = new StaticRouter()
  staticRouter.props = { location: req.url, context: {}, basename: '' }
  const { props: { history: staticHistory } } = staticRouter.render()
```
and then use it in:
```javascript
createStore(
    connectRouter(staticHistory)(reducer), compose(
      applyMiddleware(routerMiddleware(staticHistory), thunk)))
```
and:
```javascript
  <ConnectedRouter history={ staticHistory }>
...
```
It works but... yeah

**Comment by kaleidoc0de** [comment]
I haven't written up or tested anything but
I'd propose defining an environment variable in webpack to check if it is destined for the browser
and then use the correct type of history object to pass to the router reducer
`
import { createMemoryHistory, createBrowserHistory } from 'history'
`
...
`
const History = (process.env.BROWSER) ? createBrowserHistory() : createMemoryHistory
`
...
`
connectRouter(History)(rootReducer)
`

**Comment by kaleidoc0de** [comment]
after trying the above, I recieved the following error message.
`
Warning: Failed prop type: The prop 'history.listen' is marked as required in 'ConnectedRouter', but its value is 'undefined'.
`

I'll have a closer look at connected router to see if some support can be added for a memory history object

**Comment by paradoxxxzero** [comment]
Maybe react-router should expose the StaticRouter history for direct use?

**Comment by Neophy7e** [comment]
@paradoxxxzero Your solution seems to work well on my side, beside one issue I'm not sure if it's related to your solution. 

When I have server side rendering enabled the action `@@router/LOCATION_CHANGE` is being fired twice when I disable server-side rendering the action is fired normally.

Any idea where it may come from ?

**Comment by pdiniz13** [comment]
@paradoxxxzero can you post a working example of your code please?

**Comment by paradoxxxzero** [comment]
@Neophy7e I haven't tested location change server-side yet. So no sorry no idea.

@pdiniz13 My code may be summed up as:

```javascript

let history

if (SERVER) {
  const staticRouter = new StaticRouter()
  staticRouter.props = { location, context: {}, basename: '' }
  history = staticRouter.render().props.history
} else {
  history = createBrowserHistory()
}

const store = createStore(
    connectRouter(history)(reducer), state, compose(
      applyMiddleware(routerMiddleware(history), thunk)))

render(
  <Provider store={ store }>
    <ConnectedRouter history={ history }>
      <App />
    </ConnectedRouter>
  </Provider>
)
```
`location` being the server url (req.url).

**Comment by merges** [comment]
Just wondering, is there any update on how to use `connected-react-router` for sever-side rendering?

**Comment by cereallarceny** [comment]
Would love to see an update here.  Or at least some documentation on the suggested workaround @supasate.

**Comment by cereallarceny** [comment]
@supasate - I wrote a pretty in depth tutorial of how to implement SSR with Connected React Router.  It involves the suggestion above to opt into StaticRouter from React Router at the server level.

[Tutorial on Medium](https://medium.com/@cereallarceny/server-side-rendering-in-create-react-app-with-all-the-goodies-without-ejecting-4c889d7db25e)
[Example codebase](https://github.com/cereallarceny/cra-ssr)

**Comment by natterstefan** [comment]
Thank you very much @cereallarceny!

**Comment by cereallarceny** [comment]
Of course @natterstefan.  @supasate - would this tutorial be helpful in your documentation?

**Comment by cereallarceny** [comment]
@supasate Added a PR that would document server-side rendering with connected-react-router sufficiently: https://github.com/supasate/connected-react-router/pull/105
