### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by timdorr** [supasate/connected-react-router#41]
Hey @supasate. I was thinking of just emailing you, but I'd rather have this transparent and out in the open. 

I'm working on Redux integration for React Router 4.0 (to be released shortly!) and have a preliminary PR in progress here (also to be released shortly!): ReactTraining/react-router#4668 

It's really just a minimal skeleton of what the project will eventually be (hence it's getting released as an alpha). I know this project is more feature-complete and has some interesting ideas. What do you think about bringing those over to react-router-redux and working on them together under the main monorepo? 

And if that sounds like a good idea, what sort of things have you learned in bringing the react-router-redux stuff to Router 4.0? What are the biggest caveats that you still have to work through (if any)? I know this stuff is tough, so I feel your pain! 😄 

Also, feel free to email me directly (timdorr@timdorr.com) if you want to discuss anything in private.

**Comment by supasate** [comment]
Hi @timdorr. That's a great idea! I'd love to contribute to the main monorepo and join the force!

I learned many things while making this repo (especially learning how `react-router` and your awesome `react-router-redux` really work!). 

The things I love in this repo are one-way data flow to sync history and store, supporting time travelling, and supporting immutable.js (I also learn how to implement these features from people in this community also). So, I think can help contribute in these and other aspects.

Even this repo started ahead of the main repo, however, I may lack of several use-cases that you may encounter before with `react-router-redux` when being used by a large number of users. So, please advice if you find anything can be further improved. 

I'm also happy to contribute all my codebase in this repo to the new react-router-redux. 

What should we do next? Please let me know :D

**Comment by timdorr** [comment]
So, the initial 5.0 version is [pretty basic](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/ConnectedRouter.js). I'd love to work on time traveling first, since most folks are going to want that. Does your approach have any caveats when it comes to navigating and time traveling at the same time? 

First steps are to open up a PR for that. Do you want to do that first? Looks like the original version of RRR has [more extensive devtools/time traveling tests](https://github.com/reactjs/react-router-redux/blob/master/test/_createSyncTest.js#L200-L254). I'd want to also add those tests adapted for `<ConnectedRouter>` so we can be sure that use case works.

**Comment by supasate** [comment]
The current caveat is #36. If a user doesn't click the forward or back button of his/her browser, it will work perfectly. However, my actual implementation is replacing the current browser URL stack with `push` because we don't know which exact position in the stack. If we know, we can use `go` instead.

However, @zalmoxisus just made this PR zalmoxisus/redux-devtools-instrument#15 a few weeks ago which provides a listener to get what we want.

Do you want to try with the current implementation first and then fix later after the devtools's listener is available?

**Comment by supasate** [comment]
@timdorr I've made a [PR](https://github.com/ReactTraining/react-router/pull/4717) and need to discuss an issue about the initial store state and fails one of the test case.

**Comment by timdorr** [comment]
Sorry, I've been wanting to reply, but haven't been able to give it the full attention the code deserves. I'll try to get to that in the next couple days!

**Comment by eko24ive** [comment]
Hi @supasate,
It looks like your [PR](https://github.com/ReactTraining/react-router/pull/4717) was merged on 10th of May. I'd like to ask is this repo became deprecated or your features are more advanced in comparing to react-router repo? What is the current state of your collaboration on react-router package itself?
Thank you in advance for the answer !

**Comment by supasate** [comment]
Closing this issue as react-router-redux has been deprecated (https://github.com/ReactTraining/react-router/releases/tag/v4.3.0).
