### ISSUE TITLE
& can't be encoded, how to upgrade to use history v5 alpha?

### ISSUE THREAD

**Issue by kopax** [supasate/connected-react-router#411]
I am having an issue when params in url are using special char such as percent, the encoding is failed. I have opened the issue [here](https://github.com/ReactTraining/react-router/issues/7225) but I think this would be the right place.

I have seen a v5 history version and in the changelog it seems from the changelog that this issue may be fixed.

However, I was not able to upgrade `history` without issue.

This is the error I have when trying to change from the entrypoint to another route:

```
Could not find router reducer in state tree, it must be mounted under "router"
```

I can see that my reducer is well initialized for history v4.10.1, react-router 5 and connected-react-router 6.7.0, how can I perform the upgrade of `history` without breaking the connected react router ?

**Comment by timdorr** [comment]
This isn't a connect-react-router issue.

**Comment by kopax** [comment]
Ok, well I close it then, sorry for creating this. I didn't get an answer from `history` nor `react-router` as well. I am not able to upgrade the `history` to next version and not able to fix the % in url params issue. :/
