### ISSUE TITLE
Move immutable packages to optionalDependencies 

### ISSUE THREAD

**Issue by ahce** [supasate/connected-react-router#418]
Currently these packages belong to peerDependencies.

```
    "immutable": "^3.8.1 || ^4.0.0-rc.1",
    "seamless-immutable": "^7.1.3"
```

These packages are not strictly necessary.

It should be clarified  in README when these libraries are needed.

**Comment by sergei-startsev** [comment]
Should `connected-react-router/immutable` and `connected-react-router/seamless-immutable` be release as separate packages?
