### ISSUE TITLE
Route not changing - react-router 4.0.0

### ISSUE THREAD

**Issue by harmon25** [supasate/connected-react-router#42]
Was working great, but seems to be some issue with the new 4.0.0 release of react-router...
Maybe I should be posting there...

I am mostly navigating with `push` 
`@@router/LOCATION_CHANGE` actions are firing, URL bar is changing, but `Switch` doesn't appear to be matching...

Works on first load, but dispatching push just seems to change the URL...

Not getting any errors, just no routing! 😢 

Help is much appreciated!

**Comment by supasate** [comment]
Hi @harmon25,

I also try it [here](https://github.com/supasate/test-react-router-v4-with-connected-router/blob/master/src/index.js) and found no problem with `push` and `Switch`.

Could you make a minimal repo to reproduce the problem?

**Comment by harmon25** [comment]
Thanks for the response!
Your example works fine for me, trying to determine deltas as my implementation seemingly mirrors examples but experiencing this odd behaving on > v4.0.0-beta.6 of `react-router`

Just tried a couple things to no avail....
Thought maybe the `history` npm module was not aligned - installed `4.6.0` - that didn't do it...

Noticed I wasn't using `Switch` `Route` from `react-router-dom` and just importing them from `react-router` - appears as that should be OK as of [v4.0.0-beta.6](https://github.com/ReactTraining/react-router/releases/tag/v4.0.0-beta.6]) though which is the version that is working.

Think something in [v4.0.0-beta.7](https://github.com/ReactTraining/react-router/releases/tag/v4.0.0-beta.7) caused the problem - not sure why though as my implementation does not seem to differ from the examples - they also do not mention anything regarding breaking changes...

Was hoping someone else was also experiencing this... :/

Hopeful of #41 - there should really only be one package to solve the problem of connecting react-router to redux store  -  the uni-directional data flow is the right way to go.

**Comment by harmon25** [comment]
OK - should have dug a bit deeper into the new react-router docs...
this solved it [blocked-updates](https://github.com/ReactTraining/react-router/blob/v4.0.0-beta.8/packages/react-router/docs/guides/blocked-updates.md) 

Looks like I had an `<UpdateBlocker>`

Thanks for the help!

**Comment by supasate** [comment]
Good to hear that!

**Comment by sjatkins** [comment]
I honestly don't see how this is good.  If I hit a Link or other route event I expect to route and render what I routed to.  Period.  I don't see how that is an unreasonable expectation.

**Comment by odonnellnoel** [comment]
I'm running into this issue too. Has it been solved?

**Comment by rickerd** [comment]
I also have this problem.
When just using Link from react-router-dom the route is not changing.. i expect this to just work.
How else should this be done?

**Comment by centrodph** [comment]
Same issue here

**Comment by sterjoski** [comment]
@centrodph I just had the same issue and fixed it by changing `<Switch>` to `<Switch location={location}>`. That way every time the location changes it will re-render.

I didn't use a `<BlockAvoider>`, no need for `withRouter` either.
