### ISSUE TITLE
dispatch(push('/bla') builds nonsense URL AND does not redirect

### ISSUE THREAD

**Issue by DianaKoenraadt** [supasate/connected-react-router#422]
My `.env` file contains

```
PUBLIC_URL=http://mywebsite/my/subproject
```

In my actionCreators, I have some action that uses `fetch` to retrieve data from a WebAPI. I want to redirect the user to the login page when a 401 occurs. 
```
fetch(process.env.WEB_API_URL + 'SomeResource', requestOptions)
	.then(response => {
		if (response.ok) {
			return response.json() as Promise<Something[]>
		} else {
			switch (response.status) {
				case 401:
					console.log(`Unauthorized (status=${response.status}), redirecting to login.`);
					dispatch(push("/loginpage"));
					break;
			}

			throw new Error(response.statusText);
		}
	})
	.then(data => {
		// Process the data if 200 OK
	});
```

Two issues:

- My URL is changed to `http://mywebsite/http://mywebsite/my/subproject/loginpage`. This **should have been** http://mywebsite/loginpage
- And also, the page is not reloaded. I stay on the old page even though the URL changes.

**Comment by codyseibert** [comment]
I'm also seeing issues using `dispatch(push(...));`, but my console prints out 
```
Uncaught (in promise) Could not find router reducer in state tree, it must be mounted under "router"
```

**Comment by efstathiosntonas** [comment]
Same here as @codyseibert

**Comment by codyseibert** [comment]
Nevermind, I got mine working.  It looks like I was accidentally using the <ConnectRouter> and <Router> at the same time...

**Comment by efstathiosntonas** [comment]
@codyseibert can you create a gist with a minimal example? Thanks

**Comment by piedrahitapablo** [comment]
I had the same issue and I had two problems:

1. As @codyseibert mentioned, I was using ´BrowserRouter´ and ´ConnectedRouter´ at the same time, for this, you can look up the example on the readme or the examples on the code
2. I was using ´history´ on its version ´5.0.0´, and it was messing with the ´LOCATION_CHANGED´ action, downgrading it to ´^4.9.0´ fixed the issue.

I hope this helps.

**Comment by lee926427** [comment]
> I had the same issue and I had two problems on my code:
> 
> 1. As @codyseibert mentioned, I was using `BrowserRouter `and `ConnectedRouter `at the same time (@efstathiosntonas, for this, you can look up the example on the readme or the examples on the code)
> 2. I was using the `history` package on its version `5.0.0`, and it was messing with the `LOCATION_CHANGED` action, downgrading it to `^4.9.0` fixed the issue.
> 
> I hope this helps.

thank @piedrahitapablo  I resolve the page update and that working. 
that's my dependencies
    "history": "^4.9.0",
    "react-router-dom": "^5.2.0",
    "connected-react-router": "^6.8.0",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3"
  The package all lastest version for my project without history, it downgrading to 4.9.0.

**Comment by efstathiosntonas** [comment]
Thanks @piedrahitapablo `history: '5.0.0'` was the issue, downgrading to `4.9.0` automagically got it fixed and the `Uncaught (in promise) Could not find router reducer in state tree, it must be mounted under "router"` was gone.

**Comment by supasate** [comment]
@efstathiosntonas This is due to React Router v5 doesn't support history v5. 

When adding history v5, I expect it should show a warning like 

`connected-react-router@6.5.2" has incorrect peer dependency "history@^4.7.2".`.

React Router v6 will use history v5.
