### ISSUE TITLE
The example app won't work with react-routers v4 that's out of beta

### ISSUE THREAD

**Issue by pdiniz13** [supasate/connected-react-router#44]
The example app works fine, but if you upgrade react-router to the released version 4.0.0 it crashes with TypeError: Cannot read property 'location' of undefined. Any ideas as to what could be causing this?

**Comment by pdiniz13** [comment]
This https://github.com/supasate/test-react-router-redux seems to be working fine. So i'm not sure whats the difference between the two

**Comment by Elyx0** [comment]
@pdiniz13 The repo you mentionned contains   "react-router-redux": "^4.0.8" and doesn't leverage connected-react-router. I'm also not sure which way is the best way to go between the two. Maybe @supasate would know

**Comment by supasate** [comment]
Hi @pdiniz13, could you provide me more detail?
- When does it crash? (initial load, change location, etc)
- Could you provide me a minimal repo causing such error? I tried upgrading react-router to v4.0.0 and it still works fine.

Thanks!

**Comment by supasate** [comment]
I just released v4.0.0 (out of beta) which uses react-router@4.0.0. The examples are also updated to use the latest release. 

@pdiniz13 If you still face the problem, please let me know. (A minimal repo that reproducing the problem will be appreciated).

**Comment by Elyx0** [comment]
react-router-redux@next has fixed these issues too so I guess it's fine.

**Comment by pdiniz13** [comment]
@supasate the issue was that I had upgraded react-router but react-router-dom was still running on beta. Once i upgraded react-router-dom it solved the problem. I think its safe to close this.

**Comment by supasate** [comment]
Good to hear that :)
