### ISSUE TITLE
Problem with dispatching 

### ISSUE THREAD

**Issue by strelov1** [supasate/connected-react-router#443]
I call push in saga 
`yield put(push('/'));`

And I get the error herer
https://github.com/supasate/connected-react-router/blob/master/src/selectors.js#L13
The same problem with Link to

Contains: store.render
![image](https://user-images.githubusercontent.com/10761735/89393218-28f95200-d713-11ea-9187-c98f8e38b63c.png)

In redux tool
![image](https://user-images.githubusercontent.com/10761735/89393964-2519ff80-d714-11ea-9e29-7ceef0a2f5a0.png)

**Comment by Gycianka** [comment]
Duplicate of #429

Just downgrade history to v4 for now:)

**Comment by strelov1** [comment]
Thanks, It's work!
