### ISSUE TITLE
Doesn't support "basename" prop correct

### ISSUE THREAD

**Issue by hauptrolle** [supasate/connected-react-router#46]
Hi, 

I have a problem when switching from "BrowserRouter" to your "ConnectedRouter".
On the router I have the prop "basename" set to "/foo/". So i want all my routes to be prefixed with /foo. For example "/foo/bar".
The connected router ignores the basename and serves all routes from /

**Comment by supasate** [comment]
You can do that by passing it to `createBrowserHistory`.

Ex.
```js
const history = createBrowserHistory({
  basename: '/foo/',
})
```

**Comment by hauptrolle** [comment]
Nice, thank you! 😃

**Comment by supasate** [comment]
I just updated the [doc](https://github.com/supasate/connected-react-router/blob/master/FAQ.md#how-to-set-router-props-eg-basename-initialentries-etc).
