### ISSUE TITLE
error in ConnectedRouter when unsubscribe called with null store state

### ISSUE THREAD

**Issue by djeeg** [supasate/connected-react-router#48]
Am getting this error

> toJS is undefined ConnectedRouter/_this.unsubscribe<@webpack:///./~/connected-react-router/lib/ConnectedRouter.js?:54:13

Think it is coming from here
https://github.com/supasate/connected-react-router/blob/master/src/ConnectedRouter.js#L28

**Comment by supasate** [comment]
Could you help provide a minimal repo that causes this problem?

**Comment by supasate** [comment]
Please feel free to re-open this issue if someone also has this problem and can provide reproducible repo.
