### ISSUE TITLE
Uncaught Could not find router reducer in state tree, it must be mounted under "router"

### ISSUE THREAD

**Issue by huonglt** [supasate/connected-react-router#511]
I am using reducerReducer in our react app with connected-rect-router v4.
I am trying to upgrade my app to use connected-react-router v^6.0.0, along with react-router and redux to latest version.
However I got the error:
Uncaught Could not find router reducer in state tree, it must be mounted under "router"
I found out that it would require a  massive refactor of our app (change to use combineReducers) in order to work with connected-react-router v^6.0.0
Any ideas how to make our app be able to use connected-react-router v^6.0.0 without making massive code change?

**Comment by huonglt** [comment]
OK. I know how to fix it

**Comment by myufa** [comment]
How did you fix this??

**Comment by huonglt** [comment]
I changed in the main method to cater for reducer as object of { key, value} where value is a function. and key is 'router' for react router
