### ISSUE TITLE
Initial page load

### ISSUE THREAD

**Issue by rakeshpai** [supasate/connected-react-router#52]
Sorry if this is a basic question, but I couldn't find an answer, and I'm new to react/redux/router.

When the page loads initially, this module doesn't seem to dispatch any redux action. I have a URL, say /user/add, which displays a form to add a new user. When this URL is hit, I want to create a dummy user object with default values in the state, for the purposes of displaying the form correctly and holding it's data temporarily.

The above works fine if I navigate to the URL from other parts of my app, and the LOCATION_CHANGE action is dispatched correctly. However, if this URL was the first page loaded in the app, the LOCATION_CHANGE action isn't fired, which prevents me from setting up the dummy state, causing my app to break.

Is this is the expected behaviour? If so, what's the recommended workaround for handing my case?

I've tried explicitly calling `history.push(location.pathname)` on page load, and while that does the trick, it has the effect of appending to history, which is not what I want.

I'm using a static server as a backend (no server rendering), and want to stick with stateless functional components if I can.

**Comment by supasate** [comment]
Yes, it's the expected behavior.  So, some components that need the location state can get it immediately when the page loaded without waiting for another dispatching.

In your case, can you use componentDidMount in your form to set state?

**Comment by rakeshpai** [comment]
I could use componentDidMount. Certainly works for now. But I wanted to see if I can do this with only stateless components. Thanks for the answer! :)
