### ISSUE TITLE
Initial Route Not Recorded In Actions

### ISSUE THREAD

**Issue by LiquidHelium** [supasate/connected-react-router#58]
More of a request than a bug.

I could be wrong but currently it looks like the initial route is gotten through the initial state of the reducer. This means it is not recorded in the actions history exported by redux-dev-tools. So importing the history and time traveling wont work properly unless you import in the same initial route as it was recorded in.

Could we initially dispatch a location-change action with the initial route so the initial route is recorded in the action history.

**Comment by franciscolourenco** [comment]
@supasate Would you welcome a PR with this change?

**Comment by supasate** [comment]
Fixed in #96.
