### ISSUE TITLE
Could not find a declaration file for module 'connected-react-router/immutable'

### ISSUE THREAD

**Issue by tonoslav** [supasate/connected-react-router#60]
After I started to use typescript, can I at least ignore it somehow ?

**Comment by tonoslav** [comment]
My Fix until it is added 

1. Create file for example **types.d.ts**
2. Type `declare module 'connected-react-router/immutable';` and save
3. Add into **tsconfig.json**
```js
{
...
"files": [
        "types.d.ts",
        ...
 ]
...
}
```

**Comment by hsz** [comment]
This issue is still present.

**Comment by thomschke** [comment]
Any good news?

**Comment by tonoslav** [comment]
still ignored error problem even it is really easy to fix for @supasate
