### ISSUE TITLE
Deploy to Subdirectory

### ISSUE THREAD

**Issue by jhwheeler** [supasate/connected-react-router#69]
The sysadmin on our team needs to deploy our app to a subdirectory of the root url, rather than a subdomain (as I've always done it in the past).

I found various guides on how to do this with react-router, but nothing for this package. 

Is there a straightforward way to do this? And if not...is there a roundabout way? ;)

Thanks!

**Comment by Ciaran0** [comment]
I would suggest trying
```
const history = createBrowserHistory({ basename: '/folder/blah' });
```

**Comment by huyz** [comment]
So there's no equivalent to [basename in react-router](https://reacttraining.com/react-router/web/api/BrowserRouter/basename-string)? 

@jhwheeler Did you get this working?

**Comment by kprocks86** [comment]
Thanks brother @Ciaran0  it working with this
```
const history = createBrowserHistory({ basename: '/folder/blah' });
```

**Comment by jhwheeler** [comment]
A bit of a late reply, sorry about that -- but thank you @Ciaran0!
