### ISSUE TITLE
Make release compatible with redux 4

### ISSUE THREAD

**Issue by MikaelUmaN** [supasate/connected-react-router#80]
Hi. I noticed you upped compatibility with Redux 4.

Is it possible to make a maintenance release for this? Redux 4 is quite a change from 3.x.

**Comment by shincysl** [comment]
Hi, we use the package from npm. Could you help to publish a release for the change? Thank you!

**Comment by taime** [comment]
I don't get it:
"**react-router-redux**": "^4.0.8" **works with redux 4** and it's deprecated.
**connected-react-router** is newer version of ConnectedRouter from deprecated react-router-redux but it **only work with redux 3**

Is everything right? Why new version doesn't support redux4? Will it support it later or there is something wrong with redux4 and nobody should use it now?

**Comment by HSpens** [comment]
For those struggling with `npm install --save connected-react-router` reporting 

> unmet dependency redux@^3.6.0 for connected-react-router@4.3.0

Uninstall connected-react-router with `npm uninstall --save connected-react-router` and install it from the git repository with `npm install --save git+https://github.com/supasate/connected-react-router.git` instead until it is updated on npmjs.

**Comment by branchard** [comment]
@Jtango18 This is because `npm install --save git+https://github.com/supasate/connected-react-router.git` does not include `\lib` directory which contains the primary entry point of the lib
One of the solutions is to build the lib manually :confused:

**Comment by supasate** [comment]
Released v4.4.0 today and listed redux 4.x in peerDependency :). Sorry for keeping you guys waiting!
