### ISSUE TITLE
How can I access the params

### ISSUE THREAD

**Issue by thmohd** [supasate/connected-react-router#85]
I managed to make this work in my project, however, I don't see params.
`location:
hash:""
key:"aymkl8"
pathname: "/about/mo/18HHaYQSUs6WUWIOMaYYiI"
search:""`

I need to access the id (18HHaYQSUs6WUWIOMaYYiI) in MapStateToProps. I see the id in the params normally inside the component.

**Comment by axZerk** [comment]
There is a reason why route params are not included in redux state. What you probably want is this.

```js
const mapState = (state, ownProps) => {
  const { id } = ownProps.match.params;`
   // rest of your mapState code
}
```

**Comment by thmohd** [comment]
Thank you very much, that works.

**Comment by em** [comment]
What's the reason? To access matched params through `ownProps` you would need to wrap your components in `withRouter` HOC which entirely defeats the purpose of using this lib. What am I missing?

**Comment by piu130** [comment]
@em see [here](https://github.com/supasate/connected-react-router/issues/38).

**Comment by ashrafxcoder** [comment]
How about accessing `params` from a custom redux middleware that dispatches actions based on location changes

**Comment by bchelli** [comment]
Hello there, any news on gettings the params from a redux reducer?

**Comment by bchelli** [comment]
Actually, there is a ticket still opened on this topic
https://github.com/supasate/connected-react-router/issues/38
