### ISSUE TITLE
Question on react-router docs about redux "deep integration"

### ISSUE THREAD

**Issue by jacargentina** [supasate/connected-react-router#89]
The docs https://reacttraining.com/react-router/web/guides/redux-integration state: 

<img width="892" alt="captura de pantalla 2018-07-04 a la s 19 20 58" src="https://user-images.githubusercontent.com/517228/42295387-1d9fc3d2-7fc0-11e8-9e55-ab649d690cf1.png">

I have my app which uses redux, and the store has an array ok books indexed by id.

On BookDetails ( a connected component) i had the **selected book id** on the state, so i could get the full book instance, and render its **title**; ie:

```jsx
<AppBar>
  <BookTitle />
</AppBar>
<BookDetails />
```

```jsx
class BookDetails ...

const mapStateToProps = (state) => {
  const id = state.ui.selected_id;
  return {
    bookDetails: state.books.find(b => b.id == id)
  };
};
```

I have other component on the hierarchy <BookTitle /> which was also connected in a similar way, and shows the title inside the global <AppBar /> 

```jsx
class BookTitle ...

const mapStateToProps = (state) => {
  const id = state.ui.selected_id;
  return {
    title: state.books.find(b => b.id == id).title
  };
};
```

Now trying to integrate react-router (migrating away from having the **selected book id** on the store, to having now the router/match, etc) to point to the selected book.  So, i would have some like: 

```jsx
<AppBar>
  <BookTitle />
</AppBar>
<Route path='/book/:id' component={BookDetails} />
```

```jsx
class BookDetails ...

const mapStateToProps = (state, ownProps) => {
  const id = ownProps.match.params.id;
  return {
    bookDetails: state.books.find(b => b.id == id)
  };
};
```
 And also:

```jsx
class BookTitle ...

const mapStateToProps = (state, ownProps) => {
  const id = ownProps.match.params.id;   // WRONG! there is no match... so...
  return {
    title: state.books.find(b => b.id == id).title
  };
};
```

In this case, as `<BookTitle />` is not part of any `<Route path= ... />` then i cannot access _ownProps.match.params.id_  ... and then cannot know which is the selected id.... etc

if i want _to avoid using connected-react-router_ as the docs try to convince me, how would be **The Way** to access the book instance on <BookTitle />, given the current location from react-router?

**Comment by marekciupak** [comment]
```es6
import {withRouter} from 'react-router';

// ....

export default withRouter(connect(...)(BookTitle));
```

https://reacttraining.com/react-router/web/api/withRouter

**Comment by jacargentina** [comment]
@marekciupak that is useless...

**Comment by marekciupak** [comment]
@jacargentina 

Why? As I understand it, you want to pass `match` as a prop to your component. You can achieve this by wrapping it in a `withRouter`.

> `withRouter` will pass updated match, location, and history props to the wrapped component whenever it renders.

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md#withrouter

Alternatively, you could render your component using `Route`:

```es6
<AppBar>
  <Route path="/" component={BookTitle} />
</AppBar>
```

**Comment by jacargentina** [comment]
Because match is passed only when there is a match on the current component is it is wrapped in a route

That second option you give will not match  anything (it doesn't contain any Params) so.... 🤔

**Comment by marekciupak** [comment]
Ah, ok, I see. But you could add the params, right?

```jsx
<AppBar>
  <Route path='/book/:id' component={BookTitle} />
</AppBar>
<Route path='/book/:id' component={BookDetails} />
```

I'm just guessing here, because I don't know the context of your app, but perhaps this route should be higher in the hierarchy:

```jsx
<Route path='/book/:id' component={BookPageContainer} />
```

`BookPageContainer` could get the book from the redux state and pass it as a prop to nested dummy components (`BookTitle`, `BookDetails`). Alternatively, `BookPageContainer` could pass `bookId` as a prop to the nested containers.

**Comment by jacargentina** [comment]
Yeah! You have me the key to solve it: I should get the bookid in some top level component, then pass it to child who need it to fetch the book instance, etc

Thanks!
